# 服务器配置
server:
  port: 8081
  session:
    cookie:
      max-age: 1800
      http-only: true
spring:
  profiles:
    active: dev
  jpa:
#    显示程序运行中的SQL语句
    show-sql: true
    properties:
      hibernate:
#        格式化SQL语句以便于更清晰的查看运行状况
        format_sql: true
#        配置数据库环境方言
        dialect: org.hibernate.dialect.MySQL5Dialect
#        默认值即true
    open-in-view: true
---
# 开发环境数据库可以自己单独配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/erpm?useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data: debug
---
# 生产环境的数据库配置不能够进行修改
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erpm?useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: cyteam